borders: Rounded
colors:
  text: Reset
  text_special: Reset
  text_secondary: Reset
  text_error: LightRed
  outline: Reset
  outline_selected: LightBlue
  outline_hover: LightRed
  outline_secondary: LightYellow
  message_outline: '#a6ea31'
  message_error_outline: LightRed
  message_success_outline: LightGreen
  command_capture: '#a6e3a1'
  item_info:
    tag: Gray
    title: LightBlue
    description: Gray
    author: LightGreen
    viewcount: LightYellow
    length: LightCyan
    published: LightMagenta
    video_count: '#b4befe'
    sub_count: '#fab387'
    likes: '#f38ba8'
    genre: '#a6e3a1'
    page_turner: Gray
