set -ag status-style fg=#cdd6f4,bg=#1111b

set -ag message-style fg=#b4befe bg=#11111b

set-window-option -g window-status-fg #cdd6f4
set-window-option -g window-status-bg #11111b

set-window-option -g window-status-current-fg #11111b
set-window-option -g window-status-current-bg #b4befe
