set -g status-style "fg=#cdd6f4,bg=#1111b"

set -g message-style "fg=#b4befe, bg=#11111b"

set -g window-status-style "fg = #cdd6f4, bg = #11111b"

set -g window-status-current-styla "fg = 11111b, bg = #b4befe"
